package org.freeciv.admin.persistence.pojos;

import java.util.Date;

/**
 * GameResults generated by hbm2java.
 */
public class GameResult implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	private Integer id;

	/** The player one. */
	private String playerOne;

	/** The player two. */
	private String playerTwo;

	/** The winner. */
	private String winner;

	/** The end date. */
	private Date endDate;

	/**
	 * Instantiates a new game results.
	 */
	public GameResult() {
		/* nothing to do. */
	}

	/**
	 * Instantiates a new game results.
	 *
	 * @param playerOne the player one
	 * @param playerTwo the player two
	 * @param winner    the winner
	 * @param endDate   the end date
	 */
	public GameResult(String playerOne, String playerTwo, String winner, Date endDate) {
		this.playerOne = playerOne;
		this.playerTwo = playerTwo;
		this.winner = winner;
		this.endDate = endDate;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Gets the player one.
	 *
	 * @return the player one
	 */
	public String getPlayerOne() {
		return this.playerOne;
	}

	/**
	 * Sets the player one.
	 *
	 * @param playerOne the new player one
	 */
	public void setPlayerOne(String playerOne) {
		this.playerOne = playerOne;
	}

	/**
	 * Gets the player two.
	 *
	 * @return the player two
	 */
	public String getPlayerTwo() {
		return this.playerTwo;
	}

	/**
	 * Sets the player two.
	 *
	 * @param playerTwo the new player two
	 */
	public void setPlayerTwo(String playerTwo) {
		this.playerTwo = playerTwo;
	}

	/**
	 * Gets the winner.
	 *
	 * @return the winner
	 */
	public String getWinner() {
		return this.winner;
	}

	/**
	 * Sets the winner.
	 *
	 * @param winner the new winner
	 */
	public void setWinner(String winner) {
		this.winner = winner;
	}

	/**
	 * Gets the end date.
	 *
	 * @return the end date
	 */
	public Date getEndDate() {
		return this.endDate;
	}

	/**
	 * Sets the end date.
	 *
	 * @param endDate the new end date
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
