package org.freeciv.admin.persistence.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GamesPlayedStats generated by hbm2java.
 */
@Entity
@Table(name = "games_played_stats")
public class GamePlayedStat implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private GamePlayedStatId id;

	/** The game count. */
	@Column(name = "gameCount")
	private Integer gameCount;

	/**
	 * Instantiates a new games played stats.
	 */
	public GamePlayedStat() {
		/* nothing to do. */
	}

	/**
	 * Instantiates a new games played stats.
	 *
	 * @param id the id
	 */
	public GamePlayedStat(GamePlayedStatId id) {
		this.id = id;
	}

	/**
	 * Instantiates a new games played stats.
	 *
	 * @param id        the id
	 * @param gameCount the game count
	 */
	public GamePlayedStat(GamePlayedStatId id, Integer gameCount) {
		this.id = id;
		this.gameCount = gameCount;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public GamePlayedStatId getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(GamePlayedStatId id) {
		this.id = id;
	}

	/**
	 * Gets the game count.
	 *
	 * @return the game count
	 */
	public Integer getGameCount() {
		return this.gameCount;
	}

	/**
	 * Sets the game count.
	 *
	 * @param gameCount the new game count
	 */
	public void setGameCount(Integer gameCount) {
		this.gameCount = gameCount;
	}

}
