package org.freeciv.admin.persistence.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GoogleAuth generated by hbm2java.
 */
@Entity
@Table(name = "google_auth")
public class GoogleAuth implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	/** The username. */
	@Column(name = "username")
	private String username;

	/** The subject. */
	@Column(name = "subject")
	private String subject;

	/** The email. */
	@Column(name = "email")
	private String email;

	/** The activated. */
	@Column(name = "activated")
	private Integer activated;

	/** The ip. */
	@Column(name = "ip")
	private String ip;

	/**
	 * Instantiates a new google auth.
	 */
	public GoogleAuth() {
		/* nothing to do. */
	}

	/**
	 * Instantiates a new google auth.
	 *
	 * @param username  the username
	 * @param subject   the subject
	 * @param email     the email
	 * @param activated the activated
	 * @param ip        the ip
	 */
	public GoogleAuth(String username, String subject, String email, Integer activated, String ip) {
		this.username = username;
		this.subject = subject;
		this.email = email;
		this.activated = activated;
		this.ip = ip;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Gets the username.
	 *
	 * @return the username
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * Sets the username.
	 *
	 * @param username the new username
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * Gets the subject.
	 *
	 * @return the subject
	 */
	public String getSubject() {
		return this.subject;
	}

	/**
	 * Sets the subject.
	 *
	 * @param subject the new subject
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * Gets the email.
	 *
	 * @return the email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Sets the email.
	 *
	 * @param email the new email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Gets the activated.
	 *
	 * @return the activated
	 */
	public Integer getActivated() {
		return this.activated;
	}

	/**
	 * Sets the activated.
	 *
	 * @param activated the new activated
	 */
	public void setActivated(Integer activated) {
		this.activated = activated;
	}

	/**
	 * Gets the ip.
	 *
	 * @return the ip
	 */
	public String getIp() {
		return this.ip;
	}

	/**
	 * Sets the ip.
	 *
	 * @param ip the new ip
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

}
