package org.freeciv.admin.persistence.pojos;

/**
 * ServersId generated by hbm2java.
 */
public class ServerId implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The host. */
	private String host;

	/** The port. */
	private int port;

	/**
	 * Instantiates a new servers id.
	 */
	public ServerId() {
		/* nothing to do. */
	}

	/**
	 * Instantiates a new servers id.
	 *
	 * @param host the host
	 * @param port the port
	 */
	public ServerId(String host, int port) {
		this.host = host;
		this.port = port;
	}

	/**
	 * Gets the host.
	 *
	 * @return the host
	 */
	public String getHost() {
		return this.host;
	}

	/**
	 * Sets the host.
	 *
	 * @param host the new host
	 */
	public void setHost(String host) {
		this.host = host;
	}

	/**
	 * Gets the port.
	 *
	 * @return the port
	 */
	public int getPort() {
		return this.port;
	}

	/**
	 * Sets the port.
	 *
	 * @param port the new port
	 */
	public void setPort(int port) {
		this.port = port;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServerId))
			return false;
		ServerId castOther = (ServerId) other;

		return ((this.getHost() == castOther.getHost()) || (this.getHost() != null && castOther.getHost() != null
				&& this.getHost().equals(castOther.getHost()))) && (this.getPort() == castOther.getPort());
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		int result = 17;
		result = 37 * result + (getHost() == null ? 0 : this.getHost().hashCode());
		result = 37 * result + this.getPort();
		return result;
	}

}
