package org.freeciv.admin.persistence.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HallOfFame generated by hbm2java.
 */
@Entity
@Table(name = "hall_of_fame", catalog = "freeciv_web")
public class HallOfFame implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The id. */
	@Id
	@Column(name = "id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	/** The username. */
	@Column(name = "value")
	private String username;

	/** The nation. */
	@Column(name = "nation")
	private String nation;

	/** The score. */
	@Column(name = "score")
	private Integer score;

	/** The end turn. */
	@Column(name = "endTurn")
	private String endTurn;

	/** The end date. */
	@Column(name = "endDate")
	private Date endDate;

	/** The ip. */
	@Column(name = "ip")
	private String ip;

	/**
	 * Instantiates a new hall of fame.
	 */
	public HallOfFame() {
		/* nothing to do. */
	}

	/**
	 * Instantiates a new hall of fame.
	 *
	 * @param username the username
	 * @param nation   the nation
	 */
	public HallOfFame(String username, String nation) {
		this.username = username;
		this.nation = nation;
	}

	/**
	 * Instantiates a new hall of fame.
	 *
	 * @param username the username
	 * @param nation   the nation
	 * @param score    the score
	 * @param endTurn  the end turn
	 * @param endDate  the end date
	 * @param ip       the ip
	 */
	public HallOfFame(String username, String nation, Integer score, String endTurn, Date endDate, String ip) {
		this.username = username;
		this.nation = nation;
		this.score = score;
		this.endTurn = endTurn;
		this.endDate = endDate;
		this.ip = ip;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Gets the username.
	 *
	 * @return the username
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * Sets the username.
	 *
	 * @param username the new username
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * Gets the nation.
	 *
	 * @return the nation
	 */
	public String getNation() {
		return this.nation;
	}

	/**
	 * Sets the nation.
	 *
	 * @param nation the new nation
	 */
	public void setNation(String nation) {
		this.nation = nation;
	}

	/**
	 * Gets the score.
	 *
	 * @return the score
	 */
	public Integer getScore() {
		return this.score;
	}

	/**
	 * Sets the score.
	 *
	 * @param score the new score
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * Gets the end turn.
	 *
	 * @return the end turn
	 */
	public String getEndTurn() {
		return this.endTurn;
	}

	/**
	 * Sets the end turn.
	 *
	 * @param endTurn the new end turn
	 */
	public void setEndTurn(String endTurn) {
		this.endTurn = endTurn;
	}

	/**
	 * Gets the end date.
	 *
	 * @return the end date
	 */
	public Date getEndDate() {
		return this.endDate;
	}

	/**
	 * Sets the end date.
	 *
	 * @param endDate the new end date
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * Gets the ip.
	 *
	 * @return the ip
	 */
	public String getIp() {
		return this.ip;
	}

	/**
	 * Sets the ip.
	 *
	 * @param ip the new ip
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

}
