package org.freeciv.admin.persistence.domain;

import java.io.Serializable;

import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;

/**
 * PlayersId generated by hbm2java.
 */
@Embeddable
public class PlayerId implements Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The hostport. */
	@NotNull
	private String hostport;

	/** The name. */
	@NotNull
	private String name;

	/**
	 * Instantiates a new players id.
	 */
	public PlayerId() {
		/* nothing to do. */
	}

	/**
	 * Instantiates a new players id.
	 *
	 * @param hostport the hostport
	 * @param name     the name
	 */
	public PlayerId(String hostport, String name) {
		this.hostport = hostport;
		this.name = name;
	}

	/**
	 * Gets the hostport.
	 *
	 * @return the hostport
	 */
	public String getHostport() {
		return this.hostport;
	}

	/**
	 * Sets the hostport.
	 *
	 * @param hostport the new hostport
	 */
	public void setHostport(String hostport) {
		this.hostport = hostport;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlayerId))
			return false;
		PlayerId castOther = (PlayerId) other;

		return ((this.getHostport() == castOther.getHostport()) || (this.getHostport() != null
				&& castOther.getHostport() != null && this.getHostport().equals(castOther.getHostport())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())));
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		int result = 17;
		result = 37 * result + (getHostport() == null ? 0 : this.getHostport().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
